version: "3.8"

services:
  web:
    build: .
    ports:
      - "${WEB_PORT:-3000}:${WEB_PORT:-3000}"
    environment:
      - "DB_USER=${DB_USER}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_SERVER=${DB_SERVER}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_PORT=${DB_PORT}"
